version: '3.7'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  becas_api:
    build:
      context: ./api-becas
    environment:
      DEBUG: app:*
      ELASTICSEARCH_HOST: http://elastic:9200
    stdin_open: true
    command: [ "yarn", "backpack" ]
    ports:
      - 8000:3000
    volumes:
      - ./api-becas:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - elastic

  becas_web:
    build:
      context: ./web-becas
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - ./web-becas:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - becas_api

  becas_web_nginx:
    build:
      context: ./nginx
    entrypoint: ["/app/wait-for-it.sh", "becas_api:3000", "--", "nginx", "-g", "daemon off;"]
    volumes:
      - ./web-becas/public:/usr/share/nginx/html/web-becas
    ports:
      - 8080:80
    depends_on:
      - becas_web
      - becas_api

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200

volumes:
  elastic-data: