version: '3.7'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ=UTC
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  api:
    build:
      context: ./api-becas
    entrypoint: ["waitforit", "-address", "http://elastic:9200", "-timeout", "120", "--", "/start.sh"]
    environment:
      TZ: UTC
      ELASTIC_HOST: http://elastic:9200
    ports:
      - 3001:80
    links:
      - elastic
    depends_on:
      - elastic

  nginx:
    build:
      context: ./nginx
    entrypoint: ["waitforit", "-address", "http://api:80", "-timeout", "120", "--", "nginx", "-g", "daemon off;"]
    environment:
      TZ: UTC
    ports:
      - 3000:80
    links:
      - api
    depends_on:
      - api

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - 5601:5601
    environment:
      TZ: UTC
      ELASTICSEARCH_HOSTS: http://elastic:9200

volumes:
  elastic-data:
